In [10]:
import os
import zipfile
from kaggle.api.kaggle_api_extended import KaggleApi

# 1. Initialize and authenticate the API
api = KaggleApi()
api.authenticate()

# 2. Force Kaggle to download the dataset as a ZIP archive
# Notice we do NOT use the "-f sales_profit.csv" part here
dataset_slug = 'vikas605/sales-profit'
print("Downloading dataset archive...")
api.dataset_download_files(dataset_slug, path='.', unzip=False)

# 3. Kaggle names the downloaded zip after the end of the slug
zip_filename = 'sales-profit.zip'

# 4. Ankit Bansal's 2-line extraction code!
print(f"Extracting {zip_filename}...")
with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
    zip_ref.extractall('.')

print("✨ Success! The zip file was downloaded and extracted. 'sales_profit.csv' is ready!")

Downloading dataset archive...
Dataset URL: https://www.kaggle.com/datasets/vikas605/sales-profit
Extracting sales-profit.zip...
✨ Success! The zip file was downloaded and extracted. 'sales_profit.csv' is ready!

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
import pandas as pd
import os
print(os.listdir())

import pandas as pd
df = pd.read_csv("sales_profit.csv", encoding="latin1")
df.head()

['.blip-device-dedupe-id', '.conda', '.ipynb_checkpoints', '.ipython', '.jupyter', '.kaggle', '.matplotlib', '.ms-ad', '.pymol', '.pymoltimestamp', '.python_history', '.skiko', '.vscode', 'Airline data analysis.ipynb', 'ansel', 'AppData', 'Application Data', 'cancer detection.ipynb', 'Contacts', 'Cookies', 'data.csv', 'Documents', 'Downloads', 'Favorites', 'kaggle', 'Links', 'Local Settings', 'Microsoft', 'MKCL ERA Live Browser', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{d91d7dd1-f2e7-11ef-a984-d2da458be825}.TM.blf', 'NTUSER.DAT{d91d7dd1-f2e7-11ef-a984-d2da458be825}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{d91d7dd1-f2e7-11ef-a984-d2da458be825}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'PrintHood', 'product_sales_dataset_final.csv', 'Recent', 'sales-profit.zip', 'Sales_data.csv', 'sales_profit.csv', 'sales_profit.ipynb', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'travel.sqlite', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Videos']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
df = df.rename(columns={'Order ID':'order_ID', 'City':'city'})

In [4]:
df

,Row ID,order_ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,city,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [5]:
df.shape

(9994, 21)

In [6]:
df.columns = df.columns.str.lower()

In [7]:
df.columns

Index(['row id', 'order_id', 'order date', 'ship date', 'ship mode',
       'customer id', 'customer name', 'segment', 'country', 'city', 'state',
       'postal code', 'region', 'product id', 'category', 'sub-category',
       'product name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='object')

In [8]:
df.head(5)

,row id,order_id,order date,ship date,ship mode,customer id,customer name,segment,country,city,...,postal code,region,product id,category,sub-category,product name,sales,quantity,discount,profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [8]:
df['cost'] = df['sales'] - df['profit']
df.head(5)

,row id,order_id,order date,ship date,ship mode,customer id,customer name,segment,country,city,...,region,product id,category,sub-category,product name,sales,quantity,discount,profit,cost
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,220.0464
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,512.3580
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,7.7486
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,1340.6085
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,19.8516

In [9]:
df.dtypes

row id             int64
order_id          object
order date        object
ship date         object
ship mode         object
customer id       object
customer name     object
segment           object
country           object
city              object
state             object
postal code        int64
region            object
product id        object
category          object
sub-category      object
product name      object
sales            float64
quantity           int64
discount         float64
profit           float64
cost             float64
dtype: object

In [10]:
df['order date'] = pd.to_datetime(df['order date'], format='%m/%d/%Y')

In [11]:
df.head(5)

,row id,order_id,order date,ship date,ship mode,customer id,customer name,segment,country,city,...,region,product id,category,sub-category,product name,sales,quantity,discount,profit,cost
0,1,CA-2016-152156,2016-11-08,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,220.0464
1,2,CA-2016-152156,2016-11-08,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,512.3580
2,3,CA-2016-138688,2016-06-12,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,7.7486
3,4,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,1340.6085
4,5,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,19.8516

In [21]:
df['ship date'] = pd.to_datetime(df['ship date'], format='%m/%d/%Y')

In [22]:
df.head(5)

,row id,order id,order date,ship date,ship mode,customer id,customer name,segment,country,city,...,region,product id,category,sub-category,product name,sales,quantity,discount,profit,cost
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,220.0464
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,512.3580
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,7.7486
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,1340.6085
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,19.8516

In [13]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [14]:
df.head(5)

,row id,order_id,order date,ship date,ship mode,customer id,customer name,segment,country,city,state,postal code,region,product id,category,sub-category,product name,sales,quantity,discount,profit,cost
0,1,CA-2016-152156,2016-11-08,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,220.0464
1,2,CA-2016-152156,2016-11-08,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,512.3580
2,3,CA-2016-138688,2016-06-12,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,7.7486
3,4,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,1340.6085
4,5,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,19.8516

In [16]:
df['cost'] = df['sales'] - df['profit']

In [17]:
df.columns

Index(['row id', 'order_id', 'order date', 'ship date', 'ship mode',
       'customer id', 'customer name', 'segment', 'country', 'city', 'state',
       'postal code', 'region', 'product id', 'category', 'sub-category',
       'product name', 'sales', 'quantity', 'discount', 'profit', 'cost'],
      dtype='object')

In [18]:
df.dtypes

row id                    int64
order_id                 object
order date       datetime64[ns]
ship date                object
ship mode                object
customer id              object
customer name            object
segment                  object
country                  object
city                     object
state                    object
postal code               int64
region                   object
product id               object
category                 object
sub-category             object
product name             object
sales                   float64
quantity                  int64
discount                float64
profit                  float64
cost                    float64
dtype: object

In [19]:
df.drop(columns=['discount','cost'], inplace = True)

In [20]:
df.head(5)

,row id,order_id,order date,ship date,ship mode,customer id,customer name,segment,country,city,state,postal code,region,product id,category,sub-category,product name,sales,quantity,profit
0,1,CA-2016-152156,2016-11-08,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,41.9136
1,2,CA-2016-152156,2016-11-08,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,219.5820
2,3,CA-2016-138688,2016-06-12,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,6.8714
3,4,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,-383.0310
4,5,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,2.5164

In [18]:
df.columns
#df.drop(columns=['Row ID'], inplace=True)

Index(['row id', 'order_id', 'order date', 'ship date', 'ship mode',
       'customer id', 'customer name', 'segment', 'country', 'city', 'state',
       'postal code', 'region', 'product id', 'category', 'sub-category',
       'product name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='object')

In [18]:
pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.3-cp314-cp314-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.51-cp314-cp314-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 10.0 MB/s  0:00:00
Downloading greenlet-3.5.3-cp314-cp314-win_amd64.whl (240 kB)
Installing collected packages: greenlet, sqlalchemy

   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   ---------------------------------------- 2/2 [sqlalchemy]

Successfully installed greenlet-3.5.3 sqlalchemy-2.0.51
Note: you may need to restart the kernel to use updated packages.

In [23]:
pip install pymysql

Requirement already satisfied: pymysql in .\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

In [24]:
import sqlalchemy as sal

engine = sal.create_engine(
    "mysql+pymysql://root:Admin%40123@localhost:3306/amit"
)

conn = engine.connect()
print("Connected Successfully!")

Connected Successfully!

In [25]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SHOW DATABASES;"))

    for row in result:
        print(row)

('amit',)
('ananya',)
("b'script file 7'",)
('class',)
('double_join',)
('information_schema',)
('lokesh',)
('mysql',)
('performance_schema',)
('ram',)
('rama',)
('sys',)

In [7]:
import sqlalchemy as sal

engine = sal.create_engine(
    "mysql+pymysql://root:Admin%40123@localhost:3306/amit"
)

In [9]:
import pandas as pd


df.to_sql(
    'sales_data',
    con=engine,
    index=False,
    if_exists='append'
)

OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'Row ID' in 'field list'")
[SQL: INSERT INTO sales_data (`Row ID`, `Order ID`, `Order Date`, `Ship Date`, `Ship Mode`, `Customer ID`, `Customer Name`, `Segment`, `Country`, `City`, `State`, `Postal Code`, `Region`, `Product ID`, `Category`, `Sub-Category`, `Product Name`, `Sales`, `Quantity`, `Discount`, `Profit`) VALUES (%(Row_ID)s, %(Order_ID)s, %(Order_Date)s, %(Ship_Date)s, %(Ship_Mode)s, %(Customer_ID)s, %(Customer_Name)s, %(Segment)s, %(Country)s, %(City)s, %(State)s, %(Postal_Code)s, %(Region)s, %(Product_ID)s, %(Category)s, %(Sub-Category)s, %(Product_Name)s, %(Sales)s, %(Quantity)s, %(Discount)s, %(Profit)s)]
[parameters: [{'Row_ID': 1, 'Order_ID': 'CA-2016-152156', 'Order_Date': '11/8/2016', 'Ship_Date': '11/11/2016', 'Ship_Mode': 'Second Class', 'Customer_ID': 'CG-12520', 'Customer_Name': 'Claire Gute', 'Segment': 'Consumer', 'Country': 'United States', 'City': 'Henderson', 'State': 'Kentucky', 'Postal_Code': 42420, 'Region': 'South', 'Product_ID': 'FUR-BO-10001798', 'Category': 'Furniture', 'Sub-Category': 'Bookcases', 'Product_Name': 'Bush Somerset Collection Bookcase', 'Sales': 261.96, 'Quantity': 2, 'Discount': 0.0, 'Profit': 41.9136}, {'Row_ID': 2, 'Order_ID': 'CA-2016-152156', 'Order_Date': '11/8/2016', 'Ship_Date': '11/11/2016', 'Ship_Mode': 'Second Class', 'Customer_ID': 'CG-12520', 'Customer_Name': 'Claire Gute', 'Segment': 'Consumer', 'Country': 'United States', 'City': 'Henderson', 'State': 'Kentucky', 'Postal_Code': 42420, 'Region': 'South', 'Product_ID': 'FUR-CH-10000454', 'Category': 'Furniture', 'Sub-Category': 'Chairs', 'Product_Name': 'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back', 'Sales': 731.94, 'Quantity': 3, 'Discount': 0.0, 'Profit': 219.582}, {'Row_ID': 3, 'Order_ID': 'CA-2016-138688', 'Order_Date': '6/12/2016', 'Ship_Date': '6/16/2016', 'Ship_Mode': 'Second Class', 'Customer_ID': 'DV-13045', 'Customer_Name': 'Darrin Van Huff', 'Segment': 'Corporate', 'Country': 'United States', 'City': 'Los Angeles', 'State': 'California', 'Postal_Code': 90036, 'Region': 'West', 'Product_ID': 'OFF-LA-10000240', 'Category': 'Office Supplies', 'Sub-Category': 'Labels', 'Product_Name': 'Self-Adhesive Address Labels for Typewriters by Universal', 'Sales': 14.62, 'Quantity': 2, 'Discount': 0.0, 'Profit': 6.8714}, {'Row_ID': 4, 'Order_ID': 'US-2015-108966', 'Order_Date': '10/11/2015', 'Ship_Date': '10/18/2015', 'Ship_Mode': 'Standard Class', 'Customer_ID': 'SO-20335', 'Customer_Name': "Sean O'Donnell", 'Segment': 'Consumer', 'Country': 'United States', 'City': 'Fort Lauderdale', 'State': 'Florida', 'Postal_Code': 33311, 'Region': 'South', 'Product_ID': 'FUR-TA-10000577', 'Category': 'Furniture', 'Sub-Category': 'Tables', 'Product_Name': 'Bretford CR4500 Series Slim Rectangular Table', 'Sales': 957.5775, 'Quantity': 5, 'Discount': 0.45, 'Profit': -383.031}, {'Row_ID': 5, 'Order_ID': 'US-2015-108966', 'Order_Date': '10/11/2015', 'Ship_Date': '10/18/2015', 'Ship_Mode': 'Standard Class', 'Customer_ID': 'SO-20335', 'Customer_Name': "Sean O'Donnell", 'Segment': 'Consumer', 'Country': 'United States', 'City': 'Fort Lauderdale', 'State': 'Florida', 'Postal_Code': 33311, 'Region': 'South', 'Product_ID': 'OFF-ST-10000760', 'Category': 'Office Supplies', 'Sub-Category': 'Storage', 'Product_Name': "Eldon Fold 'N Roll Cart System", 'Sales': 22.368, 'Quantity': 2, 'Discount': 0.2, 'Profit': 2.5164}, {'Row_ID': 6, 'Order_ID': 'CA-2014-115812', 'Order_Date': '6/9/2014', 'Ship_Date': '6/14/2014', 'Ship_Mode': 'Standard Class', 'Customer_ID': 'BH-11710', 'Customer_Name': 'Brosina Hoffman', 'Segment': 'Consumer', 'Country': 'United States', 'City': 'Los Angeles', 'State': 'California', 'Postal_Code': 90032, 'Region': 'West', 'Product_ID': 'FUR-FU-10001487', 'Category': 'Furniture', 'Sub-Category': 'Furnishings', 'Product_Name': 'Eldon Expressions Wood and Plastic Desk Accessories, Cherry Wood', 'Sales': 48.86, 'Quantity': 7, 'Discount': 0.0, 'Profit': 14.1694}, {'Row_ID': 7, 'Order_ID': 'CA-2014-115812', 'Order_Date': '6/9/2014', 'Ship_Date': '6/14/2014', 'Ship_Mode': 'Standard Class', 'Customer_ID': 'BH-11710', 'Customer_Name': 'Brosina Hoffman', 'Segment': 'Consumer', 'Country': 'United States', 'City': 'Los Angeles', 'State': 'California', 'Postal_Code': 90032, 'Region': 'West', 'Product_ID': 'OFF-AR-10002833', 'Category': 'Office Supplies', 'Sub-Category': 'Art', 'Product_Name': 'Newell 322', 'Sales': 7.28, 'Quantity': 4, 'Discount': 0.0, 'Profit': 1.9656}, {'Row_ID': 8, 'Order_ID': 'CA-2014-115812', 'Order_Date': '6/9/2014', 'Ship_Date': '6/14/2014', 'Ship_Mode': 'Standard Class', 'Customer_ID': 'BH-11710', 'Customer_Name': 'Brosina Hoffman', 'Segment': 'Consumer', 'Country': 'United States', 'City': 'Los Angeles', 'State': 'California', 'Postal_Code': 90032, 'Region': 'West', 'Product_ID': 'TEC-PH-10002275', 'Category': 'Technology', 'Sub-Category': 'Phones', 'Product_Name': 'Mitel 5320 IP Phone VoIP phone', 'Sales': 907.152, 'Quantity': 6, 'Discount': 0.2, 'Profit': 90.7152}  ... displaying 10 of 9994 total bound parameter sets ...  {'Row_ID': 9993, 'Order_ID': 'CA-2017-121258', 'Order_Date': '2/26/2017', 'Ship_Date': '3/3/2017', 'Ship_Mode': 'Standard Class', 'Customer_ID': 'DB-13060', 'Customer_Name': 'Dave Brooks', 'Segment': 'Consumer', 'Country': 'United States', 'City': 'Costa Mesa', 'State': 'California', 'Postal_Code': 92627, 'Region': 'West', 'Product_ID': 'OFF-PA-10004041', 'Category': 'Office Supplies', 'Sub-Category': 'Paper', 'Product_Name': 'It\'s Hot Message Books with Stickers, 2 3/4" x 5"', 'Sales': 29.6, 'Quantity': 4, 'Discount': 0.0, 'Profit': 13.32}, {'Row_ID': 9994, 'Order_ID': 'CA-2017-119914', 'Order_Date': '5/4/2017', 'Ship_Date': '5/9/2017', 'Ship_Mode': 'Second Class', 'Customer_ID': 'CC-12220', 'Customer_Name': 'Chris Cortes', 'Segment': 'Consumer', 'Country': 'United States', 'City': 'Westminster', 'State': 'California', 'Postal_Code': 92683, 'Region': 'West', 'Product_ID': 'OFF-AP-10002684', 'Category': 'Office Supplies', 'Sub-Category': 'Appliances', 'Product_Name': 'Acco 7-Outlet Masterpiece Power Center, Wihtout Fax/Phone Line Protection', 'Sales': 243.16, 'Quantity': 2, 'Discount': 0.0, 'Profit': 72.948}]]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [6]:
df.describe

<bound method NDFrame.describe of       Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2016-152156   11/8/2016  11/11/2016    Second Class
1          2  CA-2016-152156   11/8/2016  11/11/2016    Second Class
2          3  CA-2016-138688   6/12/2016   6/16/2016    Second Class
3          4  US-2015-108966  10/11/2015  10/18/2015  Standard Class
4          5  US-2015-108966  10/11/2015  10/18/2015  Standard Class
...      ...             ...         ...         ...             ...
9989    9990  CA-2014-110422   1/21/2014   1/23/2014    Second Class
9990    9991  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
9991    9992  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
9992    9993  CA-2017-121258   2/26/2017    3/3/2017  Standard Class
9993    9994  CA-2017-119914    5/4/2017    5/9/2017    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

      ... Postal Code  Region       Product ID         Category Sub-Category  \
0     ...       42420   South  FUR-BO-10001798        Furniture    Bookcases
1     ...       42420   South  FUR-CH-10000454        Furniture       Chairs
2     ...       90036    West  OFF-LA-10000240  Office Supplies       Labels
3     ...       33311   South  FUR-TA-10000577        Furniture       Tables
4     ...       33311   South  OFF-ST-10000760  Office Supplies      Storage
...   ...         ...     ...              ...              ...          ...
9989  ...       33180   South  FUR-FU-10001889        Furniture  Furnishings
9990  ...       92627    West  FUR-FU-10000747        Furniture  Furnishings
9991  ...       92627    West  TEC-PH-10003645       Technology       Phones
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper
9993  ...       92683    West  OFF-AP-10002684  Office Supplies   Appliances

                                           Product Name     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2     Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                        Eldon Fold 'N Roll Cart System   22.3680         2
...                                                 ...       ...       ...
9989                             Ultra Door Pull Handle   25.2480         3
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2
9991                              Aastra 57i VoIP phone  258.5760         2
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9994 rows x 21 columns]>

In [10]:
print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

In [23]:
df.head(5)

,order_ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,city,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [11]:
pd.read_sql("DESCRIBE sales_data;", engine)

           Field           Type Null Key Default Extra
0       Order_ID            int  YES        None
1  Customer_Name    varchar(50)  YES        None
2        Product    varchar(50)  YES        None
3       Quantity            int  YES        None
4   Sales_Amount  decimal(10,2)  YES        None

In [34]:
df.to_sql(
    'sales_profit',   # New table name
    con=engine,
    if_exists='replace',
    index=False
)

9994